### ISSUE TITLE
Default mgnify database file name is wrong

### ISSUE THREAD

**Issue by tomgoddard** [hyoo/alphafold_singularity#2]
The run.sh script uses the default mgnify database file name mgy_clusters.fa

mgnify_database_path="$data_dir/mgnify/mgy_clusters.fa"

but the AlphaFold source code gives the file name as mgy_clusters_2018_12.fa as listed on the AlphaFold github

https://github.com/deepmind/alphafold

Would be nice if the run.sh script used the correct default name, otherwise runs fail with mgy_clusters.fa file not found error.

**Comment by hyoo** [comment]
yeah, it was `mgy_clusters_2018_08.fa` and renamed to `mgy_clusters_2018_12.fa`. My quick local fix was creating a symlink so that whenever the database file changes, I can refer to the same file. 
```
mgy_clusters.fa -> mgy_clusters_2018_12.fa
```
But I agree to fix the filename. Will update soon.

**Comment by tomgoddard** [comment]
Thanks!  I would put the symbolic link in but it is on a shared cluster where I don't have permissions to add a link to the AlphaFold database directories.  But I was able to proceed by editing run.sh.

**Comment by hyoo** [comment]
right, it depends on own environment, thanks for the suggestion.

**Comment by tomgoddard** [comment]
Thanks for making the singularity definition file for AlphaFold.  I have not got it running yet because our cluster database files got corrupted in a power outage and disk failure, but expect to have it going soon.  My first try at making singularity images -- it was a bad experience due to the need for root to use "singularity build" and --fakeroot not working on our CentOS 7 cluster.  I had to make the image on my desktop linux machine then transfer to the cluster (where I do not have root privileges).  But that is not an issue with your definition file, just singularity is a pain.
